name: PyPI to Anaconda

on:
  workflow_run:
    workflows: ["Upload to PyPI"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    name: PyPI to Anaconda
    steps:
      - name: pypi2anaconda
        id: p2a
        uses: rujinlong/build_anaconda_package@v1.0
        with:
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
          PYPIPKGNAME: genomediff2
