name: pytest

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install lib from source
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip pytest pandas
          python -m pip install .

      - name: Test local
        env:
          CI: true
          #PYTHONTRACEMALLOC: 10
        shell: bash -el {0}
        run: |
          python -m pytest -v --show-capture=stderr \
            tests
